ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE place
    ADD CONSTRAINT FK_PLACE_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);
